### ISSUE TITLE
Support for 1v1 Display

### ISSUE THREAD

**Issue by bllchmbrs** [SFCrime/SFC-database#8]

**Comment by bllchmbrs** [comment]
@semerj continuing conversation for comparison here with reference to commits:

https://github.com/SFCrime/SFC-database/commit/9e84523bbc92923bcc77ec651fb384176024999b

https://github.com/SFCrime/SFC-viewer/commit/15ea4b2e285c7aee3413948cbf064da48037f2f6

I think we should probably try and hit the API twice because it just keeps things simple and the backend might want to be comparison agnostic. On the other hand, I think that keeping it in one model might help with linking/story telling. I'll think about the best way to do this.

As for the stories, yeah, that's one thing that really excites me.

**Comment by bllchmbrs** [comment]
I think start_date_1 and start_date_2 is the simplest way to do this...at least for now. The better decision is probably the former one, longer term but shorter term it's a lot more work and thinking. Will update soon.

**Comment by semerj** [comment]
When you get a chance, could you add a sample geojson to the repo so I can get crackin' on the viz?

**Comment by bllchmbrs** [comment]
just get pull both and make a shape, I added in some default dates for the model so it'll give it back to you just like it would be.

If you wanted a different set, just edit the url dates, it just takes plain strings of MM-DD-YYYY and you'll get a different set.

Realistically the returned json would be the same that you would get back as it was before though.
